name: chungdam
description: "Delivery App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  google_sign_in: ^6.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  shared_preferences: ^2.3.0
  url_launcher: ^6.0.9
  intl: ^0.19.0
  bcrypt: ^1.1.3
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1  # Check for the latest version on pub.dev
  intl_phone_field: ^3.0.0
  rename_app: ^1.6.1
  http: ^1.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.5.3
  animations: ^2.0.11
  provider: ^6.0.0
  flutter_otp_text_field: ^1.1.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/aboutlogo.png
    - assets/background.png
    - assets/facebook_icon.png
    - assets/google_icon.png
    - assets/food1.jpg
    - assets/food2.jpg
    - assets/food3.jpg
    - assets/food4.jpg
    - assets/food5.jpg
    - assets/logo1.png
    - assets/background.jpg
    - assets/birthday_voucher.png
    - assets/newyear_voucher.png
    - assets/discount1.png
    - assets/discount2.png
    - assets/discount3.png
    - assets/refer_friend.png
    - assets/Malate/1m.jpg
    - assets/Malate/2m.jpg
    - assets/Malate/3m.jpg
    - assets/Malate/4m.jpg
    - assets/BGC/1b.png
    - assets/BGC/2b.jpg
    - assets/BGC/3b.jpg
    - assets/BGC/4b.jpg
    - assets/Parqal/1p.jpg
    - assets/Parqal/2p.jpg
    - assets/Parqal/3p.jpg
    - assets/Parqal/4p.png
    - assets/meat/meat1.png
    - assets/meat/meat2.png
    - assets/meat/meat3.jpg
    - assets/meat/meat4.jpg
    - assets/crab/crab1.png
    - assets/crab/crab2.png
    - assets/crab/crab3.png
    - assets/crab/crab4.jpg
    - assets/sashimi/sashimi1.jpg
    - assets/sashimi/sashimi2.jpg
    - assets/sashimi/sashimi3.jpg
    - assets/sashimi/sashimi4.jpg
    - assets/hanwooset/seta.png
    - assets/hanwooset/setb.png
    - assets/hanwooset/back.png
    - assets/background.jpg
    - assets/food1.jpg
    - assets/food2.jpg
    - assets/food3.jpg
    - assets/food4.jpg
    - assets/food5.jpg
    - assets/logo2.png
    - assets/facebook_icon.png
    - assets/google_icon.png
    - assets/birthday_voucher.png
    - assets/newyear_voucher.png
    - assets/discount1.png
    - assets/discount2.png
    - assets/discount3.png
    - assets/refer_friend.png
    - assets/visa.png
    - assets/mastercard.png
    - assets/paypal.png
    - assets/faq_icon.svg
    - assets/updateacc1.png
    - assets/updateacc2.png
    - assets/forgotpass.png
    - assets/payment.png
    - assets/hanwoo_ribeye.png
    - assets/hanwoo_skirt.png
    - assets/hanwoo_tenderloin.png
    - assets/order_confirmed.png
    - assets/image_0.png
    - assets/image_1.png
    - assets/image_2.png
    - assets/image_3.png
    - assets/image_4.png
    - assets/image_5.png
    - assets/image_6.png
    - assets/image_7.png
    - assets/image_8.png
    - assets/image_9.png
    - assets/hanwoo/myeongphumseta.png
    - assets/hanwoo/myeongphumsetamalate.png
    - assets/hanwoo/back.png
    - assets/hanwoo/shortribs.png
    - assets/hanwoo/shortribsb.png
    - assets/hanwoo/sirloin.png
    - assets/hanwoo/tenderloin.png
    - assets/hanwoo/ribeye.png
    - assets/hanwoo/skirtmeat.png
    - assets/hanwoo/ribfinger.png
    - assets/hanwoo/ribfingerb.png
    - assets/hanwoo/topblade.png
    - assets/hanwoo/topbladeb.png
    - assets/hanwoo/outsideskirtmeat.png
    - assets/hanwoo/outsideskirtmeatb.png
    - assets/hanwoo/ribeyep.png
    - assets/hanwoo/skirtmeatp.png
    - assets/hanwoo/hangingtopblade.png
    - assets/hanwoo/hangingsirloin.png
    - assets/hanwoo/hangingtender.png
    - assets/wagyu/wagyuset.png
    - assets/wagyu/back.png
    - assets/wagyu/shortribs.png
    - assets/wagyu/skirtmeat.png
    - assets/wagyu/topblade.png
    - assets/wagyu/insideskirt.png
    - assets/wagyu/chuckeyeroll.png
    - assets/wagyu/brisket.png
    - assets/usaprime/vipseta.png
    - assets/usaprime/vipsetb.png
    - assets/usaprime/back.png
    - assets/usaprime/back2.png
    - assets/usaprime/chuckeyeroll.png
    - assets/usaprime/chuckflaptail.png
    - assets/usaprime/ribeye.png
    - assets/usaprime/ribfinger.png
    - assets/usaprime/shortribs.png
    - assets/usaprime/topblade.png
    - assets/usaprime/vipsetam.png
    - assets/usaprime/vipsetbm.png
    - assets/usaprime/chuckeyerollm.png
    - assets/usaprime/chuckflaptailm.png
    - assets/usaprime/ribeyem.png
    - assets/usaprime/ribfingerm.png
    - assets/usaprime/shortribsm.png
    - assets/usaprime/topbladem.png
    - assets/samgyeopsal/ssamgyupsal.png
    - assets/samgyeopsal/sporkneck.png
    - assets/samgyeopsal/sporkjowl.png
    - assets/samgyeopsal/psamgyupsal.png
    - assets/samgyeopsal/psamgyupsalm.png
    - assets/samgyeopsal/pporkneck.png
    - assets/samgyeopsal/pporkneckm.png
    - assets/samgyeopsal/pporkjowl.png
    - assets/meal/beefpancake.png
    - assets/meal/beefpancakem.png
    - assets/meal/gyumonsausage.png
    - assets/meal/seafoodpancake.png
    - assets/meal/spamcheeseeggroll.png
    - assets/meal/spamcheeseeggrollm.png
    - assets/meal/assortedpancake.png
    - assets/meal/seafoodbuchujeon.png
    - assets/meal/ttokpokki.png
    - assets/meal/cheesettokpokki.png
    - assets/meal/frieddimsum.png
    - assets/meal/lapokki.png
    - assets/meal/noodle.png
    - assets/meal/noodlem.png
    - assets/meal/friedeggrice.png
    - assets/meal/friedeggricem.png
    - assets/meal/plainrice.png
    - assets/meal/plainricem.png
    - assets/meal/grilledpatties.png
    - assets/meal/grilledpattiesm.png
    - assets/meal/cheesegrilledpatties.png
    - assets/meal/porkbulgogi.png
    - assets/meal/porkbulgogim.png
    - assets/meal/porkneck.png
    - assets/meal/porkcutlet.png
    - assets/meal/fishcutlet.png
    - assets/meal/friedshrimp.png
    - assets/meal/cheesestick.png
    - assets/stew/bulgogibeef1.png
    - assets/stew/bulgogibeef2.png
    - assets/stew/bulgogibeefm.png
    - assets/stew/chadoldenjang.png
    - assets/stew/chadoldenjangm.png
    - assets/stew/haemuldenjang.png
    - assets/stew/kimchi.png
    - assets/stew/odeng.png
    - assets/stew/femalecrab.png
    - assets/stew/femalecrabm.png
    - assets/stew/chadoldenjangmeal.png
    - assets/stew/haemuldenjangmeal.png
    - assets/stew/beefmiyeokmeal.png
    - assets/stew/chadoldenjangmealm.png
    - assets/stew/haemuldenjangmealm.png
    - assets/stew/beefmiyeokmealm.png
    - assets/stew/koreanbeefmeal.png
    - assets/stew/kimchisoftbonemeal.png
    - assets/stew/kimchisoftbonemealm.png
    - assets/beverage/tequilajcuervo.png
    - assets/beverage/josecuervomix.png
    - assets/beverage/jinrolight.png
    - assets/beverage/svedkavodka.png
    - assets/beverage/absolutevodka.png
    - assets/beverage/hennessyvsop.png
    - assets/beverage/hennessyxo.png
    - assets/beverage/wbhoegardenm.png
    - assets/beverage/wbstellam.png
    - assets/beverage/sanmigpilsenm.png
    - assets/beverage/sanmiglightm.png
    - assets/beverage/sanmigapplem.png
    - assets/beverage/chumchurumsojum.png
    - assets/beverage/freshsojum.png
    - assets/beverage/wbhoegarden.png
    - assets/beverage/wbstella.png
    - assets/beverage/sanmigpilsen.png
    - assets/beverage/sanmiglight.png
    - assets/beverage/sanmigapple.png
    - assets/beverage/chumchurumsoju.png
    - assets/beverage/freshsoju.png
    - assets/beverage/peachsoju.png
    - assets/beverage/strawberrysoju.png
    - assets/beverage/greengrapesoju.png
    - assets/beverage/grapefruitsoju.png
    - assets/beverage/jinroisback.png
    - assets/beverage/jinroisbackm.png
    - assets/beverage/hallasan.png
    - assets/beverage/makgolli.png
    - assets/beverage/baekseju.png
    - assets/beverage/greengrapesojum.png
    - assets/beverage/grapefruitsojum.png
    - assets/beverage/makgollim.png
    - assets/beverage/baeksejum.png
    - assets/beverage/bokjunja.png
    - assets/beverage/hwayosoju17.png
    - assets/beverage/hwayosoju25.png
    - assets/beverage/hwayosoju41-375.png
    - assets/beverage/hwayosoju41-500.png
    - assets/beverage/hwayosojuxp.png
    - assets/beverage/coke.png
    - assets/beverage/cokezero.png
    - assets/beverage/sprite.png
    - assets/beverage/royal.png
    - assets/beverage/strawberry.png
    - assets/beverage/kiwi.png
    - assets/beverage/watermelon.png
    - assets/beverage/yellowmango.png
    - assets/beverage/greenmango.png
    - assets/beverage/cokem.png
    - assets/beverage/cokezerom.png
    - assets/beverage/spritem.png
    - assets/beverage/royalm.png
    - assets/beverage/strawberrym.png
    - assets/beverage/kiwim.png
    - assets/beverage/watermelonm.png
    - assets/beverage/yellowmangom.png
    - assets/beverage/greenmangom.png
    - assets/beverage/mineralwater.png
    - assets/beverage/freshlemonade.png
    - assets/beverage/solalemon.png
    - assets/beverage/solapeach.png
    - assets/beverage/pineapplejuice.png
    - assets/beverage/mangojuice.png
    - assets/beverage/solalemonm.png
    - assets/beverage/solapeachm.png
    - assets/beverage/pineapplejuicem.png
    - assets/beverage/mangojuicem.png
    - assets/specialmenumeat/beefabomasum.png
    - assets/specialmenumeat/porkabomasum.png
    - assets/specialmenumeat/beefheart.png
    - assets/specialmenumeat/beefintestine.png
    - assets/specialmenumeat/beefabomasumm.png
    - assets/specialmenumeat/porkabomasumm.png
    - assets/specialmenumeat/beefheartm.png
    - assets/specialmenumeat/beefintestinem.png
    - assets/specialmenumeat/beefribs.png
    - assets/specialmenumeat/lagalbi.png
    - assets/specialmenumeat/lagalbim.png
    - assets/specialmenumeat/gopchangset.png
    - assets/specialmenumeat/porkribs.png
    - assets/specialmenumeat/yukhwe.png
    - assets/specialmenumeat/galbihotpot.png
    - assets/specialmenumeat/galbihotpotm.png
    - assets/specialmenucrab/kingcrab.png
    - assets/specialmenucrab/freshsoycrab500.png
    - assets/specialmenucrab/freshsoycrab1000.png
    - assets/specialmenucrab/freshspicycrab500.png
    - assets/specialmenucrab/freshspicycrab1000.png
    - assets/specialmenucrab/freshsoycrab300.png
    - assets/specialmenucrab/freshsoycrab600.png
    - assets/specialmenucrab/freshspicycrab300.png
    - assets/specialmenucrab/freshspicycrab600.png
    - assets/specialmenusashimi/honmaguroset.png
    - assets/specialmenusashimi/bigeyeakami.png
    - assets/specialmenusashimi/bluefinakami.png
    - assets/specialmenusashimi/odoro.png
    - assets/specialmenusashimi/judoro.png
    - assets/specialmenusashimi/hwangsechi.png
    - assets/specialmenusashimi/betkkopsal.png
    - assets/specialmenusashimi/honmagurosashimiset1.png
    - assets/specialmenusashimi/honmagurosashimiset2.png
    - assets/specialmenusashimi/honmagurosashimiset1m.png
    - assets/specialmenusashimi/honmagurosashimiset2m.png
    - assets/specialmenusashimi/flatfish1.png
    - assets/specialmenusashimi/flatfish2.png
    - assets/specialmenusashimi/flatfish1m.png
    - assets/specialmenusashimi/flatfish2m.png
    - assets/specialmenusashimi/flatfish3.png
    - assets/specialmenusashimi/flander1.png
    - assets/specialmenusashimi/flander2.png
    - assets/specialmenusashimi/flander1m.png
    - assets/specialmenusashimi/flander2m.png
    - assets/specialmenusashimi/flander3.png
    - assets/specialmenusashimi/turbot1.png
    - assets/specialmenusashimi/turbot2.png
    - assets/specialmenusashimi/turbot1m.png
    - assets/specialmenusashimi/turbot2m.png
    - assets/specialmenusashimi/turbot3.png
    - assets/specialmenusashimi/salmonset1.png
    - assets/specialmenusashimi/salmonset2.png
    - assets/specialmenusashimi/salmonset1m.png
    - assets/specialmenusashimi/salmonset2m.png
    - assets/specialmenusashimi/freshsalmon.png
    - assets/specialmenusashimi/freshsalmonm.png
    - assets/specialmenusashimi/liveflatfish.png
    - assets/specialmenusashimi/freshsalmon+liveflatfish.png
    - assets/specialmenusashimi/grilledabalone1.png
    - assets/specialmenusashimi/grilledabalone2.png
    - assets/specialmenusashimi/steamedabalone1.png
    - assets/specialmenusashimi/steamedabalone2.png
    - assets/originfromkorea/abalonesalad.png
    - assets/originfromkorea/kodarisalad.png
    - assets/originfromkorea/kodarisaladm.png
    - assets/originfromkorea/mixedseafoodsalad.png
    - assets/originfromkorea/coldnoodlemeal.png
    - assets/originfromkorea/coldnoodledessert.png
    - assets/originfromkorea/spicycoldnoodlemeal.png
    - assets/originfromkorea/spicycoldnoodledessert.png
    - assets/originfromkorea/sokchocoldnoodlemeal.png
    - assets/originfromkorea/sokchocoldnoodledessert.png
    - assets/originfromkorea/coldnoodlemealm.png
    - assets/originfromkorea/coldnoodledessertm.png
    - assets/originfromkorea/spicycoldnoodlemealm.png
    - assets/originfromkorea/spicycoldnoodledessertm.png
    - assets/originfromkorea/sokchocoldnoodlemealm.png
    - assets/originfromkorea/sokchocoldnoodledessertm.png
    - assets/originfromkorea/freshoyster1.png
    - assets/originfromkorea/freshoyster2.png
    - assets/originfromkorea/ovenbakedoyster1.png
    - assets/originfromkorea/ovenbakedoyster2.png
    - assets/originfromkorea/gwamegi.png
    - assets/originfromkorea/elephantshell.png
    - assets/originfromkorea/liveseacucumber.png
    - assets/originfromkorea/elephantshellm.png
    - assets/originfromkorea/liveseacucumberm.png
    - assets/originfromkorea/liveseasquirt+seacucumber.png
    - assets/originfromkorea/octopussamhap.png
    - assets/originfromkorea/premiumblack.png
    - assets/originfromkorea/tongyoung.png
    - assets/originfromkorea/tongyoungm.png
    - assets/originfromkorea/beefspicysoup.png
    - assets/originfromkorea/seafoodspicysoup.png
    - assets/originfromkorea/seafoodspicysoupm.png
    - assets/icecream/peperoalmondbar.png
    - assets/icecream/jawsbar.png
    - assets/icecream/watermelonflavor.png
    - assets/icecream/wildbodycoffee.png
    - assets/icecream/screw.png
    - assets/icecream/papicochocolateflavor.png
    - assets/icecream/melonbar.png
    - assets/icecream/megaton.png
    - assets/icecream/crispycrunchbar.png
    - assets/icecream/bananamilkbar.png
    - assets/icecream/binggraebar.png
    - assets/icecream/doublebiancostrawberry.png
    - assets/icecream/espressocoffee.png
    - assets/icecream/creamcheese.png
    - assets/icecream/fanfarevanilla.png
    - assets/icecream/fanfarechocolate.png
    - assets/icecream/conechocolate.png
    - assets/icecream/conestrawberry.png
    - assets/others/background.png
    - assets/others/background2.png
    - assets/others/myeongphum.png
    - assets/others/usaprime.jpg
    - assets/others/samgyupsal.jpg
    - assets/others/singlemenu.jpg
    - assets/others/stew.jpg
    - assets/others/sashimi.png
    - assets/others/beverage.png
    - assets/others/crab.png
    - assets/others/meat.jpg
    - assets/others/originfromkorea.jpg
    - assets/others/wagyu.jpg
    - assets/others/icecream.png
