// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_MnOGUVsee0b8oHS18_qcFOAWCPIpoI',
    appId: '1:941066464553:web:3b89f3298d9c5bcb015b38',
    messagingSenderId: '941066464553',
    projectId: 'chung-dam',
    authDomain: 'chung-dam.firebaseapp.com',
    databaseURL: 'https://chung-dam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chung-dam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfgYyccbI82Gm8QbVhsha74Oazs5s6Ec',
    appId: '1:941066464553:android:de23c619c7a3ba56015b38',
    messagingSenderId: '941066464553',
    projectId: 'chung-dam',
    databaseURL: 'https://chung-dam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chung-dam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-X6ETDG4tLOCV_c4X2wsnPijqCfYoTZU',
    appId: '1:941066464553:ios:a0821ee6b0f6ffd3015b38',
    messagingSenderId: '941066464553',
    projectId: 'chung-dam',
    databaseURL: 'https://chung-dam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chung-dam.appspot.com',
    iosBundleId: 'com.example.chungdam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-X6ETDG4tLOCV_c4X2wsnPijqCfYoTZU',
    appId: '1:941066464553:ios:a0821ee6b0f6ffd3015b38',
    messagingSenderId: '941066464553',
    projectId: 'chung-dam',
    databaseURL: 'https://chung-dam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chung-dam.appspot.com',
    iosBundleId: 'com.example.chungdam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ_MnOGUVsee0b8oHS18_qcFOAWCPIpoI',
    appId: '1:941066464553:web:75318eb1c9f39cb2015b38',
    messagingSenderId: '941066464553',
    projectId: 'chung-dam',
    authDomain: 'chung-dam.firebaseapp.com',
    databaseURL: 'https://chung-dam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chung-dam.appspot.com',
  );
}
